service: hapi-serverless
provider:
  name: aws
  runtime: nodejs6.10
  stage: development
  profile: default
  region: eu-west-1

functions:
  api:
    handler: src/api/index.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true

plugins:
  - serverless-offline
